"""add_per_provider_creds

Revision ID: 0829102ccc90
Revises: e2bbb7704435
Create Date: 2026-07-10 16:24:33.707953
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0829102ccc90'
down_revision: Union[str, None] = 'e2bbb7704435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_providers', sa.Column('provider_label', sa.String(length=10), nullable=True))
    op.add_column('storage_providers', sa.Column('client_id', sa.String(length=255), nullable=True))
    op.add_column('storage_providers', sa.Column('encrypted_client_secret', sa.Text(), nullable=True))
    op.add_column('storage_providers', sa.Column('redirect_uri', sa.String(length=512), nullable=True))
    op.add_column('storage_providers', sa.Column('priority', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_providers', 'priority')
    op.drop_column('storage_providers', 'redirect_uri')
    op.drop_column('storage_providers', 'encrypted_client_secret')
    op.drop_column('storage_providers', 'client_id')
    op.drop_column('storage_providers', 'provider_label')
    # ### end Alembic commands ###
