"""life_os_upgrade

Revision ID: f7a57709f513
Revises: 0829102ccc90
Create Date: 2026-07-10 19:05:03.013136
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a57709f513'
down_revision: Union[str, None] = '0829102ccc90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_coach_insights',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_coach_insights_created_at'), 'ai_coach_insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_coach_insights_user_id'), 'ai_coach_insights', ['user_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('recurrence_rule', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_google_event_id'), 'calendar_events', ['google_event_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('user_addictions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quit_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cost_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('time_saved_per_day_mins', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_addictions_user_id'), 'user_addictions', ['user_id'], unique=False)
    op.create_table('relapse_logs',
    sa.Column('addiction_id', sa.String(length=36), nullable=False),
    sa.Column('relapsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger_notes', sa.Text(), nullable=True),
    sa.Column('mood_rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['addiction_id'], ['user_addictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relapse_logs_addiction_id'), 'relapse_logs', ['addiction_id'], unique=False)
    op.add_column('habits', sa.Column('difficulty', sa.String(length=50), nullable=True))
    op.add_column('habits', sa.Column('priority', sa.String(length=50), nullable=True))
    op.add_column('habits', sa.Column('estimated_duration', sa.Integer(), nullable=True))
    op.add_column('habits', sa.Column('color_theme', sa.String(length=50), nullable=True))
    op.add_column('habits', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('habits', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('habits', sa.Column('routine', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'routine')
    op.drop_column('habits', 'category')
    op.drop_column('habits', 'notes')
    op.drop_column('habits', 'color_theme')
    op.drop_column('habits', 'estimated_duration')
    op.drop_column('habits', 'priority')
    op.drop_column('habits', 'difficulty')
    op.drop_index(op.f('ix_relapse_logs_addiction_id'), table_name='relapse_logs')
    op.drop_table('relapse_logs')
    op.drop_index(op.f('ix_user_addictions_user_id'), table_name='user_addictions')
    op.drop_table('user_addictions')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_google_event_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_ai_coach_insights_user_id'), table_name='ai_coach_insights')
    op.drop_index(op.f('ix_ai_coach_insights_created_at'), table_name='ai_coach_insights')
    op.drop_table('ai_coach_insights')
    # ### end Alembic commands ###
